### PR TITLE
Separated align function

### PR DESCRIPTION
**Pull request by sjfox**
Copied plot aligning code from plot_grid() into a separate function, align_plots(). Now plot_grid() code reduced to simply call the aligning function. Functionality is improved, because one can align plots without having to use the plot_grid() function.

### CODE REVIEW

**Comment by clauswilke** [comment]
Can you run this through devtools::build_win() and make sure there are no errors or warnings? Thanks!

**Comment by clauswilke** [comment]
I merged this in. However, the example code for align_plots() given in the documentation doesn't make a lot of sense. Could you think about whether you can come up with a more useful example?

**Comment by sjfox** [comment]
Sure, I'll change the example.

-Spencer




On Sep 14, 2016, at 12:51, Claus Wilke <notifications@github.com> wrote:

I merged this in. However, the example code for align_plots() given in the documentation doesn't make a lot of sense. Could you think about whether you can come up with a more useful example?

**Comment by clauswilke** [comment]
This code is now on CRAN, cowplot v. 0.6.3

**Comment by sjfox** [comment]
Awesome, thanks for the update!

-Spencer




On Sep 30, 2016, at 09:52, Claus Wilke <notifications@github.com> wrote:

This code is now on CRAN, cowplot v. 0.6.3

**Pull request merged**
