### PR TITLE
Update `switch_axis.R`

### PR DESCRIPTION
**Pull request by thierrygosselin**
Update `switch_axis.R` to remove `plyr` from `DESCRIPTION Imports`

### CODE REVIEW

**Comment by clauswilke** [comment]
This is fine, but why assign the result to a variable and then return the variable? Neither the assignment nor the return statement are needed. Please look at the code of `plyr::defaults` to see what I mean.

**Comment by tbates** [comment]
@thierrygosselin I guess just a matter of amending your code to be in keeping with the requested style? 

Ditching the plyr dependency seems worth the change.

    plot_theme <- function(p) {
    	x <- p$theme
    	y <- ggplot2::theme_get()
    	c(x, y[setdiff(names(y), names(x))])
    }

**Comment by clauswilke** [comment]
Yes, that's exactly what I think the `plot_theme()` function should look like. If you could update the pull request I'll merge.

**Comment by clauswilke** [comment]
The code in question has been removed from the package.

**Pull request closed without merging**
