### PR TITLE
Flexible plot alignment

### PR DESCRIPTION
**Pull request by sjfox**
Added align_axis(), which aligns height/width size vectors. Altered align_plots() to handle complex cases (e.g. facets).

### CODE REVIEW

**Comment by clauswilke** [comment]
Spencer,

thanks for your work on this. The main issue I see is that the documentation needs to be improved or updated, for `align_axis`, `align_plots`, and `plot_grid`. For `align_axis`, from the documentation I don't get at all what it does. For `align_plots`, it seems that not all parameters are documented, or documentation is out of sync with the code. For `plot_grid`, I don't think the new functionality is explained at all.

Note that you don't have to repeat the documentation in multiple places, you can explain something in detail for one function and then just refer to that documentation from the documentation of another function.

**Comment by sjfox** [comment]
Thanks for the feedback Claus! I've tried to improve the functional documentation and examples a bit. Let me know if areas/functions are still unclear.

**Comment by clauswilke** [comment]
Almost there. The explanation for `align_axis` seems still mysterious to me, so please see if you can reword. Also, all code in the documentation should be encapsulated in `\code{...}`. See e.g. the documentation of `plot_grid`.

**Comment by sjfox** [comment]
changed the name of the `align_axis` function to `align_margin` to try to alleviate confusion, as well as edited the documentation a bit more. I included an example in the `align_margin` function which will hopefully clarify how it is used, but I wasn't thinking that it would be useful to export for people to use, as `align_plots` handles all cases that I can think of.

**Comment by clauswilke** [comment]
I'm merging this in. It's good. There is probably always room for improvement in the documentation. For example, if you're up do it, adding a few examples in the plot_grid vignette would be helpful.

**Pull request merged**
